### ISSUE TITLE
Build failed: Entry name contains invalid characters

### ISSUE THREAD

**Issue by alruiz85** [CherryPerry/GradleFileEncrypt#15]
Hello!
If I update project build.gradle to 3.3.1
`classpath 'com.android.tools.build:gradle:3.3.1'`

then I can not build my apk again with the following error:
`Entry name contains invalid characters: ../../tmpopvqFx/.empty`

No problem with build.gradle 3.2.1 version.
Thanks in advance!

**Comment by CherryPerry** [comment]
Can you build after disabling my plugin?

1. Decrypt files on old android plugin version
1. Remove encrypt plugin from gradle (or comment it)
1. Upgrade to new android plugin
1. Try to build it
1. If it can be built, try enable my plugin again and build it

Can you attach stacktrace of error? ```./gradlew assembleDebug --debug --stacktrace```

**Comment by CherryPerry** [comment]
Close issue due no response.
