### ISSUE TITLE
Add support for more gitignore features

### ISSUE THREAD

**Issue by balintbekefi** [CherryPerry/GradleFileEncrypt#21]
checkFilesGitIgnored lists files as not ignored even when they match the following command included in the .gitignore file:

> !*.encrypted

Support should be added for the gradle task to handle these filters appropriately.

**Comment by CherryPerry** [comment]
Case is fixed and [covered](https://github.com/CherryPerry/GradleFileEncrypt/pull/22/files#diff-c46b5054662f253075b15e311e0f40e2R316). I will release new version today.

Is not it easier to use private repo? You will lose all meaningful diffs of files.
