### ISSUE TITLE
mapping doesn't work

### ISSUE THREAD

**Issue by schusterro** [CherryPerry/GradleFileEncrypt#50]
Hello,

I'm on 2.0.3, and the mapping functionality doesn't work at all:

gradleFileEncrypt {
    plainFiles.from('src/main/resources/sensitive/abc.properties')
    mapping = [ 'src/main/resources/sensitive/abc.properties' : 'sensitive/xxx' ]
}

The produced encrypted file is always src/main/resources/sensitive/abc.properties.encrypted. I've also tried with files in other directories that src/main/resources, but no combination worked.

Any advice on how to make this work?

Thank you

PS: "checkFilesGitIgnored" always gives me an error with my referenced sensitive files, even if the .gitignore files in several of my projects are fine. And "checkFilesGitIgnored" from versions 2.0.3 and 2.0.2 doesn't work with a Java 1.8 runtime, because org/eclipse/jgit/api/Git is compiled for Java 11. But this is not an issue, because the main tasks seem to work fine with 1.8. (I have a strange constraint in my cloud environment, that Java 11 is not an option).

**Comment by CherryPerry** [comment]
Hm, weird, works fine for me, but I am using Java 11. Checked in my project and have a [test](https://github.com/CherryPerry/GradleFileEncrypt/blob/master/src/test/kotlin/com/cherryperry/gfe/FileEncryptPluginFunctionalTest.kt#L283) in this repo too.

Can you try using `put` instead of assign?

```kotlin
gradleFileEncrypt {
  plainFiles.from('src/main/resources/sensitive/abc.properties')
  mapping.put('src/main/resources/sensitive/abc.properties', 'sensitive/xxx')
}
```

Which Gradle version do you use?

Is it possible for you to checkout this project and run `./gradlew test --tests "com.cherryperry.gfe.FileEncryptPluginFunctionalTest.testEncryptAndDecryptMappedFile[*]"` in your environment?

Have you tried files in the root directory (not `src/main/resources`)?

**Comment by CherryPerry** [comment]
Looks like 1.8 is not really supported https://github.com/CherryPerry/GradleFileEncrypt/pull/51
I missed it.

**Comment by schusterro** [comment]
`put` has no effect, nothing happens, like before. I'm using gradle 7.4.2 and 6.8.3.
I cloned the repo and executed that command on master, but I interrupted it after 5 minutes because it just hung.
After a `clean assemble`, the command worked, but the tests have failures:

```
com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 6.8.3] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 6.9.2] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 7.0.2] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 7.1.1] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 7.2] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 7.3.3] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

com.cherryperry.gfe.FileEncryptPluginFunctionalTest > testEncryptAndDecryptMappedFile[Gradle version: 7.4.2] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at FileEncryptPluginFunctionalTest.kt:88

7 tests completed, 7 failed
```

All errors are like this:
```
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: C:\dev\github (Access is denied)
	at org.gradle.util.internal.GUtil.loadProperties(GUtil.java:247)
	at org.gradle.api.internal.plugins.PluginDescriptor.getImplementationClassName(PluginDescriptor.java:33)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:68)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:55)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3445)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2194)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2153)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3851)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3875)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4800)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.uncheckedGet(DefaultPluginRegistry.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.lookup(DefaultPluginRegistry.java:183)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.lookup(DefaultPluginRegistry.java:167)
	at org.gradle.plugin.use.resolve.service.internal.DefaultInjectedClasspathPluginResolver.resolve(DefaultInjectedClasspathPluginResolver.java:62)
	at org.gradle.plugin.use.resolve.internal.CompositePluginResolver.resolve(CompositePluginResolver.java:34)
	at org.gradle.plugin.use.resolve.internal.AlreadyOnClasspathPluginResolver.resolve(AlreadyOnClasspathPluginResolver.java:47)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:213)
	... 144 more
Caused by: java.io.FileNotFoundException: C:\dev\github (Access is denied)
	at org.gradle.util.internal.GUtil.loadProperties(GUtil.java:245)
	... 161 more
```

The project was in `C:\dev\github\!\GradleFileEncrypt`. I also tried later from `c:\dev_gradle\GradleFileEncrypt`, but the effect was the same.

I don't know what is going on here, I don't know why it wants to access that directory (as a file?).

**Comment by schusterro** [comment]
The tests work fine with jdk 11.

It's strange that jdk 1.8 is no good here, because the project is configured like this:
```
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
        apiVersion = "1.3"
    }
}
```

**Comment by CherryPerry** [comment]
> Access is denied

Do you launch Gradle as Administrator? I am wondering maybe it is actually file permissions issue.

Also please attach HTML logs for tests (build/reports/tests).

**Comment by schusterro** [comment]
No admin, there should be no permission issue because with jdk11 it worked.
But now I tried with jdk8 again, and those tests executed fine (I haven't changed absolutely anything). I then tried the tests again in that other directory with a copy of GFE, but it doesn't execute them anymore, even after a `clean assemble`. I think it's some gradle cache feature:
```
C:\dev_gradle\GradleFileEncrypt>gradlew test --tests "com.cherryperry.gfe.FileEncryptPluginFunctionalTest.testEncryptAndDecryptMappedFile[*]"
Configuration cache is an incubating feature.
Reusing configuration cache.

BUILD SUCCESSFUL in 1s
7 actionable tasks: 4 executed, 3 from cache
Configuration cache entry reused.
```
But in the first directory (C:\dev\github\\!\GradleFileEncrypt), a `clean build` then executed and I got errors in some more tests, in addition to those from yesterday. Please see the attachment.

[clean_build.errors.zip](https://github.com/CherryPerry/GradleFileEncrypt/files/9765216/clean_build.errors.zip)

**Comment by CherryPerry** [comment]
Try `--no-configuration-cache --rerun-tasks`. It will always rerun everything despite cache.

**Comment by schusterro** [comment]
Is there no more update on this?

**Comment by CherryPerry** [comment]
No, sorry. I played around a bit but could not nail the problem. I will raise the requirement to JRE 11+.
